### ISSUE TITLE
Binary for macos

### ISSUE THREAD

**Issue by 0xdabbad00** [latacora/wernicke#28]
I'm able to run `clj -m latacora.wernicke.cli` but not able to build a binary. I've never used closure or graalvm. I'm stuck because I have java 14 installed, but it looks like graalvm only supports java 8 or java 11.  I'm not sure what the path forward is.

**Comment by lvh** [comment]
Hey! Sorry I missed this. FWIW: CI builds macOS binaries now, so I'd try a recent build there: https://github.com/latacora/wernicke/actions?query=workflow%3A%22macOS+build%22

**Comment by lvh** [comment]
(I'm gonna assume that solves your issue, let me know if it doesn't :))
